# Generated by Django 3.2.4 on 2021-06-15 18:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('usertype', models.BooleanField()),
                ('block', models.CharField(default='', max_length=50)),
                ('postal', models.CharField(default='', max_length=50)),
                ('unit', models.CharField(default='', max_length=50)),
                ('lat', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('long', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('exp', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=50)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
                ('imageurl', models.CharField(default='', max_length=200)),
                ('coming', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Meetups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('imageurl', models.CharField(default='', max_length=200)),
                ('coming', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
