# Generated by Django 3.1.6 on 2021-06-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210616_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='due',
            field=models.DateTimeField(default='2021-1-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='due',
            field=models.DateTimeField(default='2021-1-15'),
            preserve_default=False,
        ),
    ]
