# Generated by Django 3.1.6 on 2021-06-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210616_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='hostname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
