# Generated by Django 3.2.4 on 2021-06-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meetups_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meetups',
            name='imageurl',
        ),
    ]
