# Generated by Django 3.2.4 on 2021-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210616_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='items',
        ),
        migrations.AlterField(
            model_name='post',
            name='coming',
            field=models.CharField(blank=True, default='NULL', max_length=50),
        ),
    ]
