# Generated by Django 3.2.4 on 2021-06-15 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210615_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), default=['a', 'adfs', 'afsdasdf'], size=None),
            preserve_default=False,
        ),
    ]
