# Generated by Django 3.2.4 on 2021-06-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210615_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tokens',
        ),
    ]
