# Generated by Django 3.1.6 on 2021-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='poop',
            field=models.CharField(default='', max_length=20),
        ),
    ]
