# Generated by Django 3.2.4 on 2021-06-14 07:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api_poop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('imageurl', models.CharField(default='', max_length=200)),
                ('coming', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=50)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
                ('imageurl', models.CharField(default='', max_length=200)),
                ('coming', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('usertype', models.BooleanField()),
                ('address', models.CharField(default='', max_length=50)),
                ('block', models.CharField(default='', max_length=50)),
                ('unit', models.CharField(default='', max_length=50)),
                ('postal', models.CharField(default='', max_length=50)),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Api',
        ),
    ]
